# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20160219_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('collaborators', models.ManyToManyField(related_name='tasks', to='todos.UserProfile')),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks', to='todos.UserProfile')),
            ],
        ),
    ]
